function = "tau.testers.run_assign"
compare = "tau.testers.test_assign"

[[exclude]]
[[exclude.nodes]]
class = "ArrayType"

[[exclude]]
[[exclude.nodes]]
class = "ArrayTypeAST"


[[exclude]]
error = "ParseErrorException"

[[exclude]]
error = "ScanError"

[[exclude]]
error = "NameError"

[[exclude]]
error = "TypeError"
