function = "tau.testers.run_codegen"
compare = "tau.testers.test_codegen"

[[exclude]]
error = "ParseErrorException"

[[exclude]]
error = "ScanError"

[[exclude]]
error = "NameError"

[[exclude]]
error = "TypeError"

[[exclude]]
pragmas = ["recursive"]

[[exclude]]
[[exclude.nodes]]
class = "ArrayTypeAST"


[[exclude]]
[[exclude.nodes]]
class = "BinaryOp"

[[exclude]]
[[exclude.nodes]]
class = "UnaryOp"

[[exclude]]
[[exclude.nodes]]
class = "UnaryOp"

[[exclude]]
[[exclude.nodes]]
class = "ParamDecl"

[[exclude]]
[[exclude.nodes]]
class = "VarDecl"

[[exclude]]
[[exclude.nodes]]
class = "ArrayType"

[[exclude]]
[[exclude.nodes]]
class = "IfStmt"

[[exclude]]
[[exclude.nodes]]
class = "WhileStmt"

[[exclude]]
[[exclude.nodes]]
class = "ReturnStmt"

[[exclude]]
[[exclude.nodes]]
class = "AssignStmt"

[[exclude]]
[[exclude.nodes]]
class = "BoolLiteral"
