function = "tau.testers.run_codegen"
compare = "tau.testers.test_codegen"


[[exclude]]
error = "ParseErrorException"

[[exclude]]
error = "ScanError"

[[exclude]]
error = "NameError"

[[exclude]]
error = "TypeError"

[[exclude]]
[[exclude.nodes]]
class = "ArrayType"

[[exclude]]
[[exclude.nodes]]
class = "ArrayTypeAST"
