function = "tau.testers.run_parser"
compare = "tau.testers.test_generic"

[[exclude]]
error = "ParseErrorException"

[[exclude]]
error = "ScanException"

[[exclude]]
[[exclude.nodes]]
class = "BinaryOp"

[[exclude]]
[[exclude.nodes]]
class = "UnaryOp"

[[exclude]]
[[exclude.nodes]]
class = "ArrayType"

[[exclude]]
[[exclude.nodes]]
class = "ArrayCell"