root = "tau.asts.AST"
inside_class = false
field_excludes = [
    "func_scope",
    "span",
    "local_scope",
    "semantic_type",
    "id",
    "token",
    "args",
]
field_opaques = [
    "register_pool",
    "register",
    "op",
    "value",
    "enclosing_function",
    "size",
]

prologue = """
# This gets incorporated in codegen.py, not a standalone!!!!!!

from tau import asts
from vm import Insn


"""


[[emit]]
roots = ["tau.asts.Expr"]
type_opaques = ["tau.asts.TypeAST", "tau.asts.Id"]
include_self = true
prefix = "_flow_"
rettype = "list[Insn]"
call = [["lab", "str"], ["condition", "bool"]]
decl = [["lab", "str"], ["condition", "bool"]]
