source = "tau/tests/syntax_error_t394.tau"
hash = "07bc1ec6240cd417570962787b144b99c137f0606415f9cc7220366d53137c62"
tokens = ["}", "int", "func", "call", "=", "or", "var", "(", ")", "true", "print", "else", ":", "if", "return", ">", "not", "false", "ID", "{", "bool", "INT", "EOF", "void", "and"]
error = "ParseErrorException"

