source = "tau/tests/syntax_error_t398.tau"
hash = "5617ecad897d1c18f38b2946fcbb9310dd465d62a85a8498c030a25e3d266759"
tokens = ["ID", "and", "var", "while", "+", "(", "{", ">", "}", ":", "EOF", ")", "void", "func", "int", "INT", "<", "print", "="]
error = "ParseErrorException"

