source = "tau/tests/syntax_error_t342.tau"
hash = "175512bf94191107a916e2596f2b4e52bd7085f717af87a4466b624a11526004"
tokens = ["int", "-", "ID", "EOF", "var", "==", ">=", "(", "print", "INT", ":", "*", ")", "{", "+", "<=", "}", "bool", ",", "/", "=", "call", "func", "void"]
error = "ParseErrorException"

