source = "tau/tests/syntax_error_t399.tau"
hash = "b6047ac784c67f1bed0668260e6cf4fdce313b67948ff3fce929fa51a6ac470e"
tokens = ["not", "and", "false", "return", "void", "or", "print", "}", "ID", "true", "var", ")", "bool", "EOF", "if", "call", ">", "=", "{", "else", "func", ":", "(", "int", "INT"]
error = "ParseErrorException"

