source = "tau/tests/syntax_error_t394.tau"
hash = "07bc1ec6240cd417570962787b144b99c137f0606415f9cc7220366d53137c62"
tokens = ["return", "call", "and", "EOF", "true", "if", "INT", "void", "{", ":", ">", "bool", "false", "or", "print", "int", "not", "ID", "var", "=", "else", "(", "}", ")", "func"]
error = "ParseErrorException"

