source = "tau/tests/syntax_error_t366.tau"
hash = "b9e44bcb411f5ab0c0c05f0abcfa6c553fcbfb9f42e0eb262bbcf00a7c0bf6d4"
tokens = [")", ":", "print", "}", "-", "int", "INT", "(", "=", "func", "{", "*", "/", "EOF", "void", "+", "ID", "var"]
error = "ParseErrorException"

