source = "tau/tests/syntax_error_t346.tau"
hash = "69d04fe75c44af16220142625ee5b499ea2ba89b58d4f71efc591a8a2e34d675"
tokens = ["+", "EOF", "while", "int", "<", "void", "func", "call", ")", "INT", "print", "=", "ID", "var", ":", "{", "(", "}", "return"]
error = "ParseErrorException"

