source = "tau/tests/syntax_error_t327.tau"
hash = "a4edc9114a00d08ea4d0cffece3eaddd7925956837aede807802221d448ca3f5"
tokens = ["void", "=", "INT", "+", "var", "ID", "EOF", ")", "func", ":", "}", "{", "print", "return", "int", "-", "("]
error = "ParseErrorException"

