source = "tau/tests/syntax_error_t311.tau"
hash = "815533b94383e541b964a76b10c62a97132f8114183527fadb436022bdb1e633"
tokens = [":", "ID", ")", "void", "INT", "print", "func", "{", "EOF", "(", "*", "}"]
error = "ParseErrorException"

