source = "tau/tests/syntax_error_t335.tau"
hash = "2aa47038c86503706f38784b75694b2bb801944bf6e8938bc85b5a22119a6859"
tokens = [":", "}", "INT", "print", "void", "else", "=", "EOF", "var", "ID", "return", "func", "bool", "or", "int", "{", ")", "if", "false", "("]
error = "ParseErrorException"

