source = "tau/tests/syntax_error_t387.tau"
hash = "0e0995602b29a5ef29c973aacabfeba49090cba67e35be7488499a90972e7824"
tokens = [":", "}", "func", "{", "EOF", "print", "void", "INT", "!=", "/", "==", ")", "(", "<", "+", "ID", "*"]
error = "ParseErrorException"

