source = "tau/tests/syntax_error_t379.tau"
hash = "e28f44db37afd1e010129d9ba13f9972ee0714f6690da3e4e1d82da59bec7794"
tokens = ["EOF", "INT", "return", "=", "(", "{", ")", "print", "ID", ":", "var", "int", "void", "}", "+", "func"]
error = "ParseErrorException"

