source = "tau/tests/syntax_error_t341.tau"
hash = "1349c992af3341bc434da786bf470fcfa0be85b861277ad13399d2b4da9582c8"
tokens = ["void", "print", "}", "INT", "(", "int", "EOF", "ID", "return", "var", "func", "+", ")", "*", ":", "/", "{", "="]
error = "ParseErrorException"

