source = "tau/tests/syntax_error_t349.tau"
hash = "1a9f0e0fe6f20bc008bf1c288a5795b8fb77a99e4b74d3f40518535183f0765f"
tokens = ["var", "if", "not", "{", "print", "<", "ID", "=", "bool", "int", "+", ")", "INT", "EOF", "(", "func", "true", "while", "void", ":", "}"]
error = "ParseErrorException"

