source = "tau/tests/syntax_error_t338.tau"
hash = "8442c90d49e1dd48c31e3e2f6c1dedaa89e2cb4f824e0f8816399a3581c8fd91"
tokens = ["int", "ID", "void", "{", "print", "INT", "bool", "(", "call", "-", "func", ",", "EOF", "+", ">=", "/", ":", "var", ")", "==", "=", "*", "<=", "}"]
error = "ParseErrorException"

