source = "tau/tests/syntax_error_t356.tau"
hash = "ea0d2c69fdb8a92b560242217086ab1e1ff0eb97056fc79c7a72e86aea048c90"
tokens = ["INT", "=", "false", "not", "ID", "func", "(", ")", "bool", ":", "var", "or", "return", "and", "print", "void", "EOF", "}", "{", "true"]
error = "ParseErrorException"

