source = "tau/tests/syntax_error_t354.tau"
hash = "7bf8d7600fa26ca329e2ac68215725a6de968edf11250347a949caede67c800b"
tokens = ["ID", "void", "EOF", "var", "if", ":", "=", "<", "func", "int", "print", "}", "else", "(", "{", "INT", ")"]
error = "ParseErrorException"

