source = "tau/tests/syntax_error_t397.tau"
hash = "474eb31f222555cba3f23eb2a4f8b4cafcaa2075e473a76c3cb9593f91f42082"
tokens = ["<=", ">", "if", "(", "==", "func", ")", "<", "{", "int", "INT", "ID", ":", "!=", "void", "}", ">=", "print", "var", "=", "EOF"]
error = "ParseErrorException"

