source = "tau/tests/syntax_error_t308.tau"
hash = "601e75286ba078b2a3673ff23a6b49361e7b406ad5d17ff1702c237760e98b6c"
tokens = [")", "INT", "void", "int", "func", "*", "=", "!=", "-", "{", "print", "EOF", "(", "ID", "}", ":", "var", "while"]
error = "ParseErrorException"

