source = "tau/tests/syntax_error_t359.tau"
hash = "592e06b0bcb5ff3fd083c2b0106d7538187a48605591be1120014f35f9944d3d"
tokens = ["void", "=", "var", "(", "print", "int", "EOF", "call", ":", "*", "{", "func", "-", ")", "ID", "INT", "+", "}", "return"]
error = "ParseErrorException"

