source = "tau/tests/syntax_error_t337.tau"
hash = "e4b2695b917b330aaafc35e5048239cbcde496d39ff67cba943a8de0d11a126d"
tokens = ["func", "INT", "var", "return", "+", "print", "}", "int", "{", "void", "(", "=", "EOF", ")", "ID", ":"]
error = "ParseErrorException"

