source = "tau/tests/syntax_error_t390.tau"
hash = "f86b95e27087851de2dcc5afa8232a9aba653410c7f8622a128034d0c7df41d5"
tokens = ["return", "else", "INT", "{", "func", "true", "}", "false", "ID", "bool", "(", "<=", "+", "while", "-", ")", "int", "=", "if", "var", ":", "print", "EOF", "=="]
error = "ParseErrorException"

