source = "tau/tests/syntax_error_t362.tau"
hash = "2358252b77db709ce87997dccb2d6c117a3482d736e78135f23a93615670db53"
tokens = ["if", "EOF", "}", "print", "INT", ":", "{", "int", "func", "else", ")", "ID", "<", "call", "(", ",", "void"]
error = "ParseErrorException"

