source = "tau/tests/syntax_error_t324.tau"
hash = "30a028e5b7de76999b657b5038c394746be87b1a13330dba83e7416cdb223c18"
tokens = ["print", "+", ",", "call", "ID", "=", "}", "/", "*", ")", "var", "(", ":", "INT", "EOF", "int", "{", "void", "func"]
error = "ParseErrorException"

