source = "tau/tests/syntax_error_t334.tau"
hash = "283fa1cd947e3068204844d0d2eee332283bc96f70e9e7334800400dbbf1680f"
tokens = ["int", "func", ")", "ID", ":", "print", "return", "EOF", "{", "+", "call", ",", "INT", "}", "void", "("]
error = "ParseErrorException"

