source = "tau/tests/syntax_error_t307.tau"
hash = "86c2403df400683941a541d6c9d59dff97bc3bac2dcc4d19fbf676686327851e"
tokens = [":", "INT", "void", ")", "func", "{", "return", "=", "int", "print", "}", ",", "(", "+", "ID", "var", "EOF", "call"]
error = "ParseErrorException"

