source = "tau/tests/syntax_error_t304.tau"
hash = "0f171f4be0a4e2f255451b896e843e45201632dba56f975588cbed97956336ae"
tokens = ["print", ">", "}", ":", "<=", "<", "!=", "ID", "func", ">=", "==", ")", "{", "EOF", "-", "(", "void", "INT"]
error = "ParseErrorException"

