source = "tau/tests/syntax_error_t388.tau"
hash = "6dffea07cd35ca684e559a6a7d236d63b9fdb7392f21e46f716a1b39f736e661"
tokens = ["(", "int", ":", ")", "print", "}", ",", "func", "call", "else", "INT", "<", "EOF", "void", "ID", "if", "{"]
error = "ParseErrorException"

