source = "tau/tests/syntax_error_t322.tau"
hash = "de3094dc04942adecda3814865b61d516507acfa9216fb99d25705e3c2e73cd5"
tokens = ["}", ")", "false", "INT", "{", "EOF", "print", "bool", "<=", "(", "ID", ":", "void", "=", "true", "var", "func"]
error = "ParseErrorException"

