source = "tau/tests/syntax_error_t363.tau"
hash = "52c9feda72c1614f1e94a32530ae0045aee7fb5a59212aadeca427ef822d3d30"
tokens = ["=", "{", "+", "void", "(", "int", "EOF", "<", "func", "ID", ")", "while", "]", "var", "INT", ":", "[", "}"]
error = "ParseErrorException"

