source = "tau/tests/syntax_error_t375.tau"
hash = "a3050cba6c6ef26f107ec42fad55c31b420c191c7b4f894fff0ed0ab2b43c330"
pragmas = ["recursive"]
tokens = ["}", ")", "ID", ",", "else", "(", "=", "int", "func", ":", "+", "-", "<", "!=", "return", "void", "{", "if", "print", "var", "INT", "EOF"]
error = "ParseErrorException"

