source = "tau/tests/syntax_error_t383.tau"
hash = "1907709ccee1da73a1efc2160891816fa5bcccaf31a87c678eccc7d45143bef1"
tokens = [")", "+", "void", "INT", "func", "print", "*", ":", "/", "EOF", "(", "}", "ID", "{"]
error = "ParseErrorException"

