source = "tau/tests/syntax_error_t355.tau"
hash = "db17f4e0c3d6236ab0f8a03deb0c0b21d801edb7abb41720f48a15beafe10724"
tokens = ["print", "var", "EOF", "(", "{", "}", "int", "=", "INT", "if", "func", ":", "ID", "<", ")", "else", "void"]
error = "ParseErrorException"

