source = "tau/tests/syntax_error_t367.tau"
hash = "4bfeb3eeb77b2663edb19c4828ed829f527353e87d702d52e9df0480db0a78dd"
tokens = ["(", "EOF", "void", "func", "*", "<=", ":", "INT", "return", "while", ")", "=", "int", "var", "{", "print", "ID", "}", "+"]
error = "ParseErrorException"

