source = "tau/tests/syntax_error_t336.tau"
hash = "7d9372ee881d33ff94d58bdef41d2b69fd7d8c5daf2340c2ea7b18b752b925b9"
tokens = ["INT", "func", "int", "}", "void", "return", "ID", "=", "var", "{", ")", "(", ":", "EOF", "print", "+"]
error = "ParseErrorException"

