source = "tau/tests/syntax_error_t381.tau"
hash = "163ff5c88536af03ca4a0655763703d9b9dd5337cf9b5f20642a21bb8f4b6d4c"
tokens = ["}", "]", "void", ")", "INT", "call", "+", "EOF", "var", "[", "(", "=", "{", "func", ":", "int", "ID"]
error = "ParseErrorException"

