source = "tau/tests/syntax_error_t332.tau"
hash = "5a2248d2a53e312384099b7a36f92c9dc64089d08deb9ae9b8b5386391ae5cf6"
tokens = ["-", "EOF", "false", ":", "print", "INT", "(", "or", "true", "and", "=", ")", "}", "if", "int", "while", "var", "func", "void", "{", "ID", "<", "bool"]
error = "ParseErrorException"

