source = "tau/tests/syntax_error_t390.tau"
hash = "f86b95e27087851de2dcc5afa8232a9aba653410c7f8622a128034d0c7df41d5"
tokens = ["bool", "(", "}", "==", "+", "<=", "true", "int", "print", "=", "else", "while", "ID", "func", "if", "false", ":", "EOF", "var", "-", "{", "return", ")", "INT"]
error = "ParseErrorException"

