source = "tau/tests/syntax_error_t333.tau"
hash = "38caf464e5ba76a824105e19387294741b2bf5528a5089e10768b3a7086f059c"
tokens = [":", "EOF", "void", "else", "or", "return", "bool", "false", ")", "(", "ID", "int", "func", "print", "=", "INT", "}", "var", "{", "if"]
error = "ParseErrorException"

