source = "tau/tests/syntax_error_t384.tau"
hash = "3e9210c6df4f1ba60f4dedb47fc1d0195b5852b357d793acc26543c096164a16"
tokens = ["INT", "print", "var", ")", "<", "{", "func", "ID", "}", "(", "EOF", "while", "return", "void", "=", ":", "+", ",", "int"]
error = "ParseErrorException"

