source = "tau/tests/syntax_error_t305.tau"
hash = "242dc962e98d431acfd41b6593ab50a7ae022b9e0f31698a7523e7f7ba44c99c"
tokens = ["func", "int", "while", "print", "(", "return", "{", "<", "EOF", "+", "}", "ID", ")", "void", "INT", "var", "=", ":"]
error = "ParseErrorException"

