source = "tau/tests/syntax_error_t395.tau"
hash = "341562fd6aa3b4bba96280d682f6bb7b057c6b06a91bb3452965cfcf4d8df774"
tokens = ["<=", "==", "ID", "EOF", ")", "if", "print", "func", ">=", "=", "int", "}", "(", "void", ">", "!=", "<", "var", "INT", "{", ":"]
error = "ParseErrorException"

