source = "tau/tests/syntax_error_t328.tau"
hash = "7ff5317694335292274ec0ae43bb09177801f6198558f1cf20608b2cf4066797"
tokens = ["var", "INT", "int", "EOF", ">", "+", "(", ")", "call", "}", "bool", "<", ":", "void", "func", "print", "=", ",", "==", "{", "ID"]
error = "ParseErrorException"

