source = "tau/tests/syntax_error_t319.tau"
hash = "19d07042a0f4d8866fc0c92b6b7385de523c5456af1803921aea621986db4bd5"
tokens = ["=", "return", "}", "(", "EOF", "+", ":", "{", "void", ")", "var", "print", "*", "INT", "-", "func", "ID", "int"]
error = "ParseErrorException"

