source = "tau/tests/syntax_error_t389.tau"
hash = "db199eeae36c418fa77c989c6adbb36cd7084dfa1e0b929146666c48935fcdc8"
tokens = ["{", "(", "void", "ID", ":", ")", "func", "+", "}", "EOF", "print", "INT"]
error = "ParseErrorException"

