source = "tau/tests/t125.tau"
hash = "12caa455e7ec92d97d685234ee477149d2b1de93c0bbbf12a69daa7bc4dab8ef"
tokens = [")", "(", "EOF", "}", "func", "print", ":", "{", "ID", "true", "void", "not"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "UnaryOp"

[[nodes]]
class = "UnaryOp"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "UnaryOp"
field = "expr"
field_type = "BoolLiteral"

[[nodes]]
class = "UnaryOp"
field = "op"
field_type = "Token"
token = "not"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "true"

[[nodes]]
class = "BoolLiteral"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolLiteral"
field = "value"
field_type = "bool"

