source = "tau/tests/t126.tau"
hash = "2decf72fa48e3f93af3001787f36ca814580f2e650b3c7183481b70ee63f43d6"
tokens = ["(", "}", ":", "-", "EOF", "void", "func", "ID", "{", "INT", "print", ")"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "BinaryOp"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "-"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IntLiteral"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

