source = "tau/tests/t131.tau"
hash = "dd2049d3ec4c0fbb8aa12f77086edec3d4af740c9ad3d1e3d1a224543e8716e4"
tokens = ["ID", ")", "print", "not", "func", "true", ":", "(", "}", "EOF", "{", "void"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "UnaryOp"

[[nodes]]
class = "UnaryOp"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "UnaryOp"
field = "op"
field_type = "Token"
token = "not"

[[nodes]]
class = "UnaryOp"
field = "expr"
field_type = "UnaryOp"

[[nodes]]
class = "UnaryOp"
field = "expr"
field_type = "BoolLiteral"

[[nodes]]
class = "BoolLiteral"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolLiteral"
field = "value"
field_type = "bool"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "true"

