source = "tau/tests/t138.tau"
hash = "50e2aa33eb0b2e8bfddad229f966122188b4afc99f903be61413be854a312f47"
tokens = ["=", "func", ":", "<", "(", "{", "bool", "EOF", ")", "}", "ID", "INT", "void", "var"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "BoolType"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "token"
field_type = "Token"
token = "bool"

[[nodes]]
class = "BoolType"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "BinaryOp"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "<"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

