source = "tau/tests/t156.tau"
hash = "9cf95667ed8e269745434b2c02b32b67de7b76a4db326fa1f8ff853fc20e03ce"
tokens = [":", "func", ")", "print", "}", "(", "void", "and", "false", "EOF", "true", "ID", "or", "INT", "{", "+"]
error = "TypeError"

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "BinaryOp"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "BinaryOp"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "or"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "BoolLiteral"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "BoolLiteral"

[[nodes]]
class = "BoolLiteral"
field = "value"
field_type = "bool"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "true"

[[nodes]]
class = "BoolLiteral"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "false"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "and"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "+"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

