source = "tau/tests/t162.tau"
hash = "b53e8368288b7fa98d6ed76fb5a780ee14d56745fa79ed25a680bd0f7ddca2e7"
tokens = ["INT", "ID", ")", "print", "(", "void", "{", "EOF", ":", "=", "func", "}"]
error = "NameError"

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "Phony_Scope"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Phony_Symbol"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "Phony_Scope"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "IntLiteral"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IdExpr"

