source = "tau/tests/t162.tau"
hash = "0b43835340a440ec23ecf71621830209c7a1de8de4f35c2de06971d1e7a0d830"
tokens = ["(", "{", "EOF", ")", "ID", "func", "}", ":", "void", "print"]
error = "NameError"

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "Phony_Scope"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Phony_Symbol"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "Phony_Scope"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

