source = "tau/tests/t174.tau"
hash = "4ec2a4dd7e194659d9b364523ee2770e84ad914eff922662bfc376a4f218fc03"
tokens = ["void", "true", "print", "{", "}", "EOF", "func", ")", "bool", "not", "var", ":", "=", "(", "ID"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "BoolType"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "token"
field_type = "Token"
token = "bool"

[[nodes]]
class = "BoolType"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "BoolLiteral"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "true"

[[nodes]]
class = "BoolLiteral"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolLiteral"
field = "value"
field_type = "bool"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "UnaryOp"

[[nodes]]
class = "UnaryOp"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "UnaryOp"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "UnaryOp"
field = "op"
field_type = "Token"
token = "not"

