source = "tau/tests/t192.tau"
hash = "cef29d14a002b119e77e9b3ed6261f6822329a8399c9de5e7a1183a91e4d2bf5"
tokens = ["INT", "print", "void", "{", "func", ":", "ID", "true", "}", "(", "false", ")", "EOF"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "BoolLiteral"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "true"

[[nodes]]
class = "BoolLiteral"
field = "value"
field_type = "bool"

[[nodes]]
class = "BoolLiteral"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "false"

