source = "tau/tests/t202.tau"
hash = "62d20ac0b1f489316e2bfcbca10cf73b580b0dc6ace87959ce3d4a00340867f6"
tokens = ["=", "INT", "(", "}", "var", "print", ":", "{", "call", "func", "return", "ID", "EOF", "int", "void", "+", ")"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "ParamDecl"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "IntType"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "ParamDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "ParamDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "ParamDecl"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "ReturnStmt"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "ReturnStmt"
field = "enclosing_function"
field_type = "FuncDecl"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "+"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IdExpr"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "CallStmt"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "IntLiteral"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "CallStmt"
field = "call"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "Argument"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "CallExpr"
field = "fn"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "CallExpr"

[[nodes]]
class = "Argument"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "IdExpr"

