source = "tau/tests/t237.tau"
hash = "b66acd834c02efdbb821a2cc0c34621d1a6848c072016bc8e7b83db02fa84e25"
tokens = ["}", "int", ":", "EOF", "+", "var", "func", "call", "ID", "void", "(", "INT", "=", "return", "{", ")"]
error = "TypeError"

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "ParamDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "ParamDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "ParamDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "ParamDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "ReturnStmt"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "IntLiteral"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "ReturnStmt"
field = "enclosing_function"
field_type = "NoneType"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "+"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IdExpr"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "CallStmt"

[[nodes]]
class = "CallStmt"
field = "call"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "Argument"

[[nodes]]
class = "CallExpr"
field = "fn"
field_type = "IdExpr"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "Argument"
field = "semantic_type"
field_type = "Phony_Type"

