source = "tau/tests/t296.tau"
hash = "e585eab992cffb63341eebbf4989404ab9cdd0c596a74d30a89491b3ff86a7eb"
tokens = [")", "{", "bool", "(", "ID", "}", "INT", "var", "if", "call", ":", "EOF", "func", "return", "else", "void", "int"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "IntType"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "ReturnStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "ReturnStmt"
field = "enclosing_function"
field_type = "FuncDecl"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "IfStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "BoolType"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "token"
field_type = "Token"
token = "bool"

[[nodes]]
class = "IfStmt"
field = "elseStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "IfStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "IfStmt"
field = "thenStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "CallStmt"

[[nodes]]
class = "CallStmt"
field = "call"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "<empty>"

[[nodes]]
class = "CallExpr"
field = "fn"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "FuncType"

