source = "tau/tests/t315.tau"
hash = "9eda69acb92760093761116d24a386bcf38b0d6bedb438726ac806c3c40bf8ec"
tokens = [")", "=", "print", "func", "INT", "{", "var", "}", "int", "EOF", ":", "void", "(", "/", "ID"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "IntLiteral"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "/"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "BinaryOp"

