source = "tau/tests/t381.tau"
hash = "d959607a6573dd254b6ac6c168982f2d4e2bc01f21b58b0091616eaa8322420b"
tokens = ["(", "call", "]", "void", "{", "int", ")", "INT", "+", "[", "}", "=", "EOF", ":", "ID", "func", "var"]
error = "ParseErrorException"

