source = "tau/tests/t382.tau"
hash = "adeb2c84d3bee0184a2fac2a84c48f4cbee4cf2fbdc4b09864e8ef80a95c5422"
tokens = [":", "func", "bool", "(", "int", ">", ")", "void", "{", "return", "INT", "ID", ",", "+", "if", "print", "false", "EOF", "}", "else", "true"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "IntType"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "ParamDecl"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "ParamDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "ParamDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "ParamDecl"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "ReturnStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "ReturnStmt"
field = "enclosing_function"
field_type = "FuncDecl"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "+"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "token"
field_type = "Token"
token = "bool"

[[nodes]]
class = "BoolType"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "IfStmt"

[[nodes]]
class = "IfStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "IfStmt"
field = "elseStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "IfStmt"
field = "thenStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "BinaryOp"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = ">"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "BoolLiteral"

[[nodes]]
class = "BoolLiteral"
field = "value"
field_type = "bool"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "false"

[[nodes]]
class = "BoolLiteral"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "true"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "IfStmt"
field = "expr"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "fn"
field_type = "IdExpr"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "Argument"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "Argument"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IntLiteral"

