source = "tau/tests/t392.tau"
hash = "50aaceaf097c855b6b0ff53f5c947924cca67e19aaa792bfbbfee29c9930a5aa"
tokens = ["{", "EOF", "void", "int", ")", "var", ",", "ID", ":", "func", "=", "(", "}", "+"]
error = "NameError"

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "ParamDecl"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "Phony_Scope"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Phony_Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "ParamDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "ParamDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "ParamDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "CompoundStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "Phony_Scope"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "BinaryOp"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "+"

