source = "tau/tests/t395.tau"
hash = "64f6a1216efd03da7af0a125b8c5b4f0980f6f3e03023e38b2eed4cadb8a0dd4"
tokens = ["int", "(", ">", "func", "<=", "var", "{", "INT", "<", "=", "EOF", "print", ")", "if", "void", ":", "ID", ">=", "==", "}", "!="]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "IfStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "IntLiteral"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IfStmt"
field = "expr"
field_type = "BinaryOp"

[[nodes]]
class = "IfStmt"
field = "elseStmt"
field_type = "NoneType"

[[nodes]]
class = "IfStmt"
field = "thenStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "BinaryOp"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BinaryOp"
field = "left"
field_type = "IdExpr"

[[nodes]]
class = "BinaryOp"
field = "right"
field_type = "IntLiteral"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = ">"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = ">="

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "<"

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "<="

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "=="

[[nodes]]
class = "BinaryOp"
field = "op"
field_type = "Token"
token = "!="

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IntLiteral"

