source = "tau/tests/t401.tau"
hash = "1d80cd121596841653b65cb704703c371488309be0a7ba4f2b2bfcef40dc677e"
tokens = ["ID", "var", "call", "void", "else", "=", "bool", "if", "EOF", ",", ":", "print", "func", "{", "(", ")", "return", "false", "true", "}"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "BoolType"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "ParamDecl"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "ParamDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "ParamDecl"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "ParamDecl"
field = "type_ast"
field_type = "BoolType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "token"
field_type = "Token"
token = "bool"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "ReturnStmt"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "ReturnStmt"
field = "enclosing_function"
field_type = "FuncDecl"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "AssignStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "IfStmt"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "BoolType"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "BoolLiteral"

[[nodes]]
class = "AssignStmt"
field = "lhs"
field_type = "IdExpr"

[[nodes]]
class = "BoolLiteral"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "BoolLiteral"
field = "value"
field_type = "bool"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "true"

[[nodes]]
class = "BoolLiteral"
field = "token"
field_type = "Token"
token = "false"

[[nodes]]
class = "IfStmt"
field = "thenStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "IfStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "IfStmt"
field = "elseStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "AssignStmt"
field = "rhs"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "Argument"

[[nodes]]
class = "CallExpr"
field = "fn"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Argument"
field = "semantic_type"
field_type = "BoolType"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "CallStmt"

[[nodes]]
class = "CallStmt"
field = "call"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "<empty>"

