source = "tau/tests/t426.tau"
hash = "eca3fb1a4fce6a44121c4758420662a7c820dadea7c3c2ef60a5a58a2ed881cd"
tokens = ["void", "INT", "}", ",", "EOF", "return", ")", "print", "func", "{", "ID", "int", "(", ":", "var"]

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "ParamDecl"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "IntType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "ParamDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "ParamDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "ParamDecl"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "VarDecl"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "CompoundStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "ReturnStmt"

[[nodes]]
class = "VarDecl"
field = "type_ast"
field_type = "IntType"

[[nodes]]
class = "VarDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "VarDecl"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "ReturnStmt"
field = "enclosing_function"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "semantic_type"
field_type = "VoidType"

[[nodes]]
class = "VoidType"
field = "token"
field_type = "Token"
token = "void"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "<empty>"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "Argument"

[[nodes]]
class = "CallExpr"
field = "fn"
field_type = "IdExpr"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "IntType"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "FuncType"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "Argument"
field = "semantic_type"
field_type = "IntType"

