source = "tau/tests/t502.tau"
hash = "52651d4cd720bc011dd54323f070826672ca572fe46d1c1b679d9354fdecc0f9"
tokens = ["func", "ID", "int", "}", "else", "{", "print", "bool", "if", "call", "EOF", "(", "return", ")", ":", "INT"]
error = "TypeError"

[[nodes]]
class = "Program"
field = "decls"
field_type = "FuncDecl"

[[nodes]]
class = "FuncDecl"
field = "body"
field_type = "CompoundStmt"

[[nodes]]
class = "FuncDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "FuncDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "FuncDecl"
field = "func_scope"
field_type = "FuncScope"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "ParamDecl"

[[nodes]]
class = "FuncDecl"
field = "ret_type_ast"
field_type = "IntType"

[[nodes]]
class = "Id"
field = "token"
field_type = "Token"
token = "ID"

[[nodes]]
class = "Id"
field = "symbol"
field_type = "Symbol"

[[nodes]]
class = "Id"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "ParamDecl"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "ParamDecl"
field = "id"
field_type = "Id"

[[nodes]]
class = "ParamDecl"
field = "type_ast"
field_type = "BoolType"

[[nodes]]
class = "BoolType"
field = "token"
field_type = "Token"
token = "bool"

[[nodes]]
class = "BoolType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IntType"
field = "token"
field_type = "Token"
token = "int"

[[nodes]]
class = "IntType"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "CompoundStmt"
field = "local_scope"
field_type = "LocalScope"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "IfStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "PrintStmt"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "ReturnStmt"

[[nodes]]
class = "CompoundStmt"
field = "decls"
field_type = "<empty>"

[[nodes]]
class = "IfStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "IfStmt"
field = "thenStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "IfStmt"
field = "elseStmt"
field_type = "NoneType"

[[nodes]]
class = "IdExpr"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IdExpr"
field = "id"
field_type = "Id"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "IntLiteral"
field = "token"
field_type = "Token"
token = "INT"

[[nodes]]
class = "IntLiteral"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "IdExpr"

[[nodes]]
class = "ReturnStmt"
field = "enclosing_function"
field_type = "NoneType"

[[nodes]]
class = "ReturnStmt"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "CompoundStmt"
field = "stmts"
field_type = "CallStmt"

[[nodes]]
class = "CallStmt"
field = "call"
field_type = "CallExpr"

[[nodes]]
class = "CallExpr"
field = "fn"
field_type = "IdExpr"

[[nodes]]
class = "CallExpr"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "CallExpr"
field = "args"
field_type = "Argument"

[[nodes]]
class = "Argument"
field = "expr"
field_type = "IntLiteral"

[[nodes]]
class = "Argument"
field = "semantic_type"
field_type = "Phony_Type"

[[nodes]]
class = "IfStmt"
field = "elseStmt"
field_type = "CompoundStmt"

[[nodes]]
class = "PrintStmt"
field = "expr"
field_type = "CallExpr"

[[nodes]]
class = "FuncDecl"
field = "params"
field_type = "<empty>"

